import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '../../auth/[...nextauth]/route';
import path from 'path';
import fs from 'fs';
import { exec } from 'child_process';
import util from 'util';

const execPromise = util.promisify(exec);

export async function POST(req: Request) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.id) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await req.json();
    const { segments, model = 'llama3', numClips = 5 } = body;

    if (!segments || !Array.isArray(segments)) {
      return NextResponse.json({ error: 'Missing or invalid segments array' }, { status: 400 });
    }

    // Write temporary json
    const tempJsonPath = path.join(process.cwd(), 'public', `temp_transcript_${Date.now()}.json`);
    fs.writeFileSync(tempJsonPath, JSON.stringify({ segments }));
    
    const outFileName = `highlights_${Date.now()}.json`;
    const outFilePath = path.join(process.cwd(), 'public', outFileName);
    
    const pythonScript = path.resolve(process.cwd(), '../../ai-engine/highlight_extractor.py');
    const cmd = `python "${pythonScript}" --json "${tempJsonPath}" --out "${outFilePath}" --model "${model}" --clips ${numClips}`;
    
    console.log(`Running Command: ${cmd}`);
    
    // Set timeout to 5 minutes (300000ms) for local LLM generation
    await execPromise(cmd, { timeout: 300000 });
    
    if (!fs.existsSync(outFilePath)) {
      fs.unlinkSync(tempJsonPath); // cleanup
      throw new Error("Output JSON not generated by Python script");
    }
    
    const rawData = fs.readFileSync(outFilePath, 'utf8');
    const parsedData = JSON.parse(rawData);
    
    // Cleanup temporary files
    fs.unlinkSync(tempJsonPath);
    fs.unlinkSync(outFilePath);
    
    return NextResponse.json({
      success: true,
      highlights: parsedData
    });

  } catch (error) {
    console.error('Highlight extractor error:', error);
    return NextResponse.json({ error: 'Internal server error', details: String(error) }, { status: 500 });
  }
}
