import { NextResponse } from 'next/server';
import { prisma } from '@audira/database';
import { getServerSession } from 'next-auth';
import { authOptions } from '../../auth/[...nextauth]/route';
import path from 'path';
import fs from 'fs';
import FormData from 'form-data';
import axios from 'axios';

// Konfigurasi endpoint AI (bisa diarahkan ke Local AI Engine atau Groq/OpenAI di masa depan)
const AI_ENGINE_URL = process.env.AI_ENGINE_URL || 'http://localhost:8000';
const GROQ_API_KEY = process.env.GROQ_API_KEY;

export async function POST(req: Request) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.id) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await req.json();
    const { videoId, language = 'id' } = body;

    if (!videoId) {
      return NextResponse.json({ error: 'Missing videoId' }, { status: 400 });
    }

    const video = await prisma.video.findUnique({
      where: { id: videoId, userId: session.user.id },
    });

    if (!video) {
      return NextResponse.json({ error: 'Video not found' }, { status: 404 });
    }

    const inputPath = path.resolve(process.cwd(), 'public', video.storagePath.replace(/^\//, ''));
    if (!fs.existsSync(inputPath)) {
      return NextResponse.json({ error: 'Source video file not found locally' }, { status: 404 });
    }

    // Gunakan Groq API jika key tersedia (FAST LANE)
    if (GROQ_API_KEY) {
      console.log(`Using GROQ Fast Lane API for subtitle generation: ${inputPath}`);
      try {
        const formData = new FormData();
        formData.append('file', fs.createReadStream(inputPath));
        formData.append('model', 'whisper-large-v3');
        formData.append('language', language);
        formData.append('response_format', 'verbose_json');

        const groqResponse = await axios.post('https://api.groq.com/openai/v1/audio/transcriptions', formData, {
          headers: {
            'Authorization': `Bearer ${GROQ_API_KEY}`,
            'Content-Type': 'multipart/form-data',
          },
        });

        return NextResponse.json({
          success: true,
          segments: groqResponse.data.segments.map((s: any) => ({
            start: s.start,
            end: s.end,
            text: s.text
          })),
          language: language,
          source: 'groq'
        });

      } catch (groqError) {
        console.error('Groq API Error:', groqError);
        return NextResponse.json({ error: 'Groq API failed', details: groqError instanceof Error ? groqError.message : 'Unknown error' }, { status: 502 });
      }
    }

    // Call Local Python AI Engine On-Demand
    try {
      console.log(`[On-Demand AI] Executing local Python script for ${inputPath}`);
      const { exec } = require('child_process');
      const util = require('util');
      const execPromise = util.promisify(exec);
      
      const outFileName = `subtitle_${Date.now()}.json`;
      const outFilePath = path.join(process.cwd(), 'public', outFileName);
      
      // Pastikan untuk menyesuaikan path ke ai-engine/main.py
      const pythonScript = path.resolve(process.cwd(), '../../ai-engine/main.py');
      
      // Jika di Windows, lebih aman membungkus path dengan tanda kutip ganda
      const cmd = `python "${pythonScript}" --audio "${inputPath}" --out "${outFilePath}" --language "${language}"`;
      
      console.log(`Running Command: ${cmd}`);
      
      // Jalankan script python
      await execPromise(cmd, { maxBuffer: 1024 * 1024 * 10 }); // 10MB buffer just in case
      
      // Baca hasil JSON
      if (!fs.existsSync(outFilePath)) {
        throw new Error("Output JSON not generated by Python script");
      }
      
      const rawData = fs.readFileSync(outFilePath, 'utf8');
      const parsedData = JSON.parse(rawData);
      
      // Bersihkan file temporary
      fs.unlinkSync(outFilePath);
      
      return NextResponse.json({
        success: true,
        segments: parsedData.segments,
        language: parsedData.language,
        source: 'local-ondemand'
      });

    } catch (aiError) {
      console.error('Local Python AI error:', aiError);
      return NextResponse.json({ 
        error: 'AI Transcription failed. Make sure Python is installed and faster_whisper is available.',
        details: aiError instanceof Error ? aiError.message : 'Unknown error'
      }, { status: 502 });
    }

  } catch (error) {
    console.error('Subtitle error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
