import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '../../auth/[...nextauth]/route';
import path from 'path';
import fs from 'fs';
import { exec } from 'child_process';
import util from 'util';

const execPromise = util.promisify(exec);

export async function POST(req: Request) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.id) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await req.json();
    const { segments, videoId } = body;

    if (!segments || !Array.isArray(segments)) {
      return NextResponse.json({ error: 'Missing or invalid segments array' }, { status: 400 });
    }

    // Write temporary json
    const tempJsonPath = path.join(process.cwd(), 'public', `temp_transcript_${Date.now()}.json`);
    fs.writeFileSync(tempJsonPath, JSON.stringify({ segments }));
    
    // Create ASS filename
    const identifier = videoId ? videoId : Date.now();
    const outFileName = `subtitle_${identifier}.ass`;
    const outFilePath = path.join(process.cwd(), 'public', outFileName);
    
    const pythonScript = path.resolve(process.cwd(), '../../ai-engine/ass_generator.py');
    const cmd = `python "${pythonScript}" --json "${tempJsonPath}" --out "${outFilePath}"`;
    
    console.log(`Running Command: ${cmd}`);
    
    await execPromise(cmd);
    
    if (!fs.existsSync(outFilePath)) {
      fs.unlinkSync(tempJsonPath); // cleanup
      throw new Error("Output ASS not generated by Python script");
    }
    
    // Cleanup temporary JSON
    fs.unlinkSync(tempJsonPath);
    
    // We don't delete outFilePath because the frontend needs to download it
    // The client can download it from /subtitle_XXXXX.ass
    
    return NextResponse.json({
      success: true,
      url: `/${outFileName}`
    });

  } catch (error) {
    console.error('ASS generator error:', error);
    return NextResponse.json({ error: 'Internal server error', details: String(error) }, { status: 500 });
  }
}
